# permissions to do viewer endpoints.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: endpoint-viewer-role
rules:
- apiGroups:
  - frp.go.build4.fun
  resources:
  - endpoints
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - frp.go.build4.fun
  resources:
  - endpoints/status
  verbs:
  - get
