
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - frp.go.build4.fun
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - frp.go.build4.fun
  resources:
  - services/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - frp.go.build4.fun
  resources:
  - endpoints
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - frp.go.build4.fun
  resources:
  - endpoints/status
  verbs:
  - get
  - patch
  - update
- apiGroups: [""]
  resources:
    - configmaps
    - pods
    - services
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
