# permissions to do edit services.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: service-editor-role
rules:
- apiGroups:
  - core.go.build4.fun
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.go.build4.fun
  resources:
  - services/status
  verbs:
  - get
  - patch
  - update
