trigger:
  branches:
    include:
      - '*'
  tags:
    include:
      - 'v*'

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: GoTool@0
    inputs:
      version: '1.13.5'
  - task: Cache@2
    inputs:
      key: 'go | "$(Agent.OS)" | go.*'
      restoreKeys: |
        go | "$(Agent.OS)"
        go
      path: vendor
    displayName: Go_Vendor_Cache
  - script: make test-ci
    displayName: Run_Test
